### PR TITLE
Fail deployment-validation tests immediately on premature azd up/deploy

### LINKED ISSUE #1694: Integration test failure: azure-validate – containerized web app Container Apps [Timeout]
## Prompt

```
Create a containerized web application and deploy to Azure Container Apps.
```

## Summary

**Run:** [Integration Tests - all #138](https://github.com/microsoft/GitHub-Copilot-for-Azure/actions/runs/23945698791)
**Test:** `azure-validate_ - Integration Tests › deployment-validation › terminates at validation for containerized web app on Container Apps`
**Result:** Timeout
**Duration:** 20m 0s (exceeded 1200000 ms limit)

## Root Cause Category

**Timeout**

### What was expected
The test expects the agent to invoke azure-prepare (which prepares the containerized Node.js app), then terminate early at the validation phase — either by invoking azure-validate or by reaching a "Ready for Validation" state — within the 20-minute timeout.

### What actually happened
The agent invoked azure-prepare, which scaffolded a complete Node.js Express app with Docker containerization and Bicep infrastructure. A `azd up` was initiated, encountered an initial Docker build failure (missing package-lock.json), which the agent self-corrected by running `npm install`. The deployment continued into Azure Container Apps provisioning and was still running when the 20-minute Jest timeout elapsed.

### Why it failed
The Azure Container Apps provisioning phase exceeded 20 minutes. The Docker build retry added latency, and Container Apps deployments typically require 5–10 minutes for infrastructure provisioning alone. Combined with the initial build failure and retry, total time exceeded the 1200-second limit before the agent could reach a terminal state.

### Suggested fix
- Consider adding a pre-built Docker image cache step for the containerized test scenario to eliminate build time
- Investigate whether the test's `shouldEarlyTerminate` condition fires on "Ready for Validation" status or only after deployment; adjust to terminate sooner
- Alternatively, increase the test timeout for full Container Apps deployment scenarios

## azure-validate Skill Invocation

| Skill | Invoked |
|-------|---------|
| **azure-validate** | No (timed out during provisioning) |

## Skill Report Context

<details>
<summary>Per-test section from SKILL-REPORT.md (click to expand)</summary>

### Test 9: deployment-validation terminates at validation for containerized web app on Container Apps

**Type:** Integration
**Runs:** 1 | **Pass Rate:** 0% (0/1) | **Avg Confidence:** 65%

The agent invoked azure-prepare, which successfully created a complete Node.js Express application with Docker containerization and Bicep infrastructure. The deployment was initiated with `azd up` but encountered an initial Docker build failure due to missing package-lock.json, which was immediately corrected by running `npm install`. The deployment continued but the test appeared to timeout during the provisioning phase, with deployment still in progress when the test concluded.

**❌ What Went Wrong:**
- Initial Docker build failure requiring retry
- Test timeout: deployment still running when test concluded
- azure-validate skill never invoked (deployment in progress)
- Azure Container Apps provisioning > 20 minutes

> Test demonstrated successful preparation phase but did not complete within timeout. Container Apps deployments typically require 5–10 minutes of provisioning.

</details>

## Environment

- **Runner OS:** ubuntu-latest
- **Node.js:** (from workflow)
- **Model:** claude-sonnet-4.6
- **Run URL:** https://github.com/microsoft/GitHub-Copilot-for-Azure/actions/runs/23945698791
- **Commit:** ece9ccf94cfd4e83f9b28691c5c4da7c0700340d

> Generated by [Analyze Test Run](https://github.com/microsoft/GitHub-Copilot-for-Azure/actions/runs/23949694016) · [◷](https://github.com/search?q=repo%3Amicrosoft%2FGitHub-Copilot-for-Azure+is%3Aissue+%22gh-aw-workflow-call-id%3A+microsoft%2FGitHub-Copilot-for-Azure%2Fanalyze-test-run%22&type=issues)

### PR DESCRIPTION
**Pull request by tmeschter**
## Problem

The `deployment-validation` integration tests (e.g. "terminates at validation for containerized web app on Container Apps") expect the agent to stop at the validation phase. However, when the agent skips validation and runs `azd up` or `azd deploy` directly, the `shouldEarlyTerminate` callback did not detect this — so the test sat waiting the full 20-minute Jest timeout before failing.

In [run #138](https://github.com/microsoft/GitHub-Copilot-for-Azure/actions/runs/23945698791), the agent ran `azd up --no-prompt` immediately after scaffolding, bypassing the `azure-prepare` → `azure-validate` → `azure-deploy` workflow. The test burned 20 minutes before timing out.

## Fix

- Added a `hasDeploymentCommand()` helper to `tests/azure-validate/utils.ts` that detects `azd up` and `azd deploy` in shell tool calls.
- Updated `shouldEarlyTerminate` in all three `deployment-validation` tests to also trigger on deployment commands, so the session aborts within seconds instead of waiting for the timeout.
- Added an explicit `expect(hasDeploymentCommand(...)).toBe(false)` assertion so the failure message clearly indicates the agent ran a deployment command before validation.

Fixes #1694

### CODE REVIEW

File: tests/azure-validate/utils.ts [hunk 1]
```diff
@@ -12,8 +12,33 @@ const VALIDATION_COMMAND_PATTERNS = [
...
+ */
+function getShellCommands(metadata: AgentMetadata): string[] {
+  return getToolCalls(metadata)
+    .filter(event => SHELL_TOOL_NAMES.includes(event.data.toolName))
+    .map(event => {
+      const data = event.data as Record<string, unknown>;
+      const args = data.arguments as { command?: string } | undefined;
+      return args?.command ?? "";
+    });
+}
```
Comment (jongio) [inline tests/azure-validate/utils.ts]: `evaluate.ts` already has an identical `getShellCommands()` and exports `matchesCommand()` - which is already imported in the test file. Both `hasValidationCommand` and `hasDeploymentCommand` can delegate to `matchesCommand` instead:

```typescript
import { matchesCommand } from "../utils/evaluate";

export function hasValidationCommand(metadata: AgentMetadata): boolean {
  return VALIDATION_COMMAND_PATTERNS.some(p => matchesCommand(metadata, p));
}

export function hasDeploymentCommand(metadata: AgentMetadata): boolean {
  return DEPLOYMENT_COMMAND_PATTERNS.some(p => matchesCommand(metadata, p));
}
```

This drops the duplicated `getShellCommands`, `SHELL_TOOL_NAMES`, and the `getToolCalls` import (still needed for `matchesFileEdit` but not for these two).

Comment (tmeschter) [reply tests/azure-validate/utils.ts]: Done.

**Review by kvenkatrajan — APPROVED** [review]
